"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import type { IndexData, RangeKey } from "@/lib/yahoo";
import { fmtPct } from "@/lib/format";

type Row = IndexData & { custom?: boolean; risk: { volatility: number | null; sharpe: number | null; sortino: number | null; maxDrawdown: number | null } };
const periods: { key: RangeKey; label: string }[] = [{ key: "1D", label: "Day" }, { key: "1W", label: "Week" }, { key: "1M", label: "Month" }, { key: "3M", label: "3 months" }, { key: "6M", label: "6 months" }, { key: "1Y", label: "Year" }, { key: "5Y", label: "5 years" }];

export default function LeaderboardTable() {
  const [period, setPeriod] = useState<RangeKey>("1M");
  const [rows, setRows] = useState<Row[]>([]);
  const [loadedPeriod, setLoadedPeriod] = useState<RangeKey | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/leaderboard?range=${period}`, { signal: controller.signal }).then(async (r) => { if (!r.ok) throw new Error("Leaderboard unavailable."); return r.json(); }).then((d: { rows: Row[] }) => { setRows(d.rows); setError(null); setLoadedPeriod(period); }).catch((e: Error) => { if (e.name !== "AbortError") setError(e.message); }); return () => controller.abort(); }, [period]);
  const loading = loadedPeriod !== period;
  return <main className="mx-auto w-full max-w-6xl px-5 py-10 sm:py-14"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-accent">Market scoreboard</p><h1 className="mt-2 text-4xl font-black tracking-tight text-foreground">Leaders by return</h1><p className="mt-3 max-w-2xl text-muted">Rankings are rebased over the same period. Sharpe and drawdown add the risk taken to get there.</p></div><div className="flex flex-wrap gap-1 rounded-2xl border border-surface bg-surface/40 p-1">{periods.map((item) => <button key={item.key} onClick={() => setPeriod(item.key)} className={`rounded-xl px-3 py-2 text-xs font-bold ${period === item.key ? "bg-accent text-white" : "text-muted hover:text-foreground"}`}>{item.label}</button>)}</div></div><div className="overflow-x-auto rounded-2xl border border-surface bg-surface/40">{loading ? <div className="p-12 text-center text-sm text-muted">Refreshing the board...</div> : error ? <div role="alert" className="p-12 text-center text-sm text-down">{error}</div> : <table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-surface bg-surface/60 text-xs uppercase tracking-wider text-muted-light"><tr><th className="px-5 py-4">#</th><th className="px-3 py-4">Index</th><th className="px-3 py-4">Return</th><th className="px-3 py-4">Sharpe</th><th className="px-3 py-4">Sortino</th><th className="px-3 py-4">Volatility</th><th className="px-3 py-4">Max drawdown</th><th className="px-5 py-4">Open</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.slug} className="border-b border-surface/70 last:border-0 hover:bg-surface/30"><td className="px-5 py-4 font-mono text-muted-light">{String(index + 1).padStart(2, "0")}</td><td className="px-3 py-4 font-bold text-foreground">{row.name}{row.custom && <span className="ml-2 rounded-full bg-accent/10 px-2 py-0.5 text-[10px] text-accent">YOU</span>}</td><td className={`px-3 py-4 font-mono font-bold ${(row.changePct ?? 0) >= 0 ? "text-up" : "text-down"}`}>{fmtPct(row.changePct)}</td><td className="px-3 py-4 font-mono text-muted">{row.risk.sharpe?.toFixed(2) ?? "-"}</td><td className="px-3 py-4 font-mono text-muted">{row.risk.sortino?.toFixed(2) ?? "-"}</td><td className="px-3 py-4 font-mono text-muted">{row.risk.volatility?.toFixed(2) ?? "-"}%</td><td className="px-3 py-4 font-mono text-down">{row.risk.maxDrawdown?.toFixed(2) ?? "-"}%</td><td className="px-5 py-4"><Link href={row.custom ? `/compare?left=${row.slug}` : `/index/${row.slug}`} className="font-semibold text-accent hover:underline">View &rarr;</Link></td></tr>)}</tbody></table>}</div><p className="mt-5 text-xs leading-relaxed text-muted-light">Risk metrics use the available observations, annualized from their sampling interval. Sharpe assumes a 0% risk-free rate. Data via Yahoo Finance, delayed.</p></main>;
}
